import Image from "next/image";
import React from "react";
import formDecor from "@/public/login-decor.svg";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/redux/Provider";
import { Toaster } from "@/components/ui/toaster";

import Setup from "@/utils/Setup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="flex justify-between h-screen min-h-[900px] w-full ">
            <div className="grow flex justify-center">{children}</div>
            <Image className="h-full w-fit" src={formDecor} alt="login-decor" />
          </div>
          <Setup />
        </Provider>
      </body>
    </html>
  );
}
