# Generated by Django 4.2.6 on 2023-10-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authorization", "0008_user_workspaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stripe_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("customer_id", models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
