# Generated by Django 4.2.6 on 2023-10-25 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authorization", "0008_user_workspaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "feature_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "price_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("nickname", models.CharField(blank=True, max_length=256, null=True)),
                ("price", models.PositiveIntegerField()),
                ("freq", models.CharField(blank=True, max_length=64, null=True)),
                ("active", models.BooleanField()),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stripe_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("customer_id", models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "subscription_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=64)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="payments.stripeuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionItem",
            fields=[
                (
                    "sub_item_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="payments.price",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.subscription",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="stripeuser",
            index=models.Index(
                fields=["user", "customer_id"], name="payments_st_user_id_2f1e3e_idx"
            ),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_products",
                to="payments.feature",
            ),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_features",
                to="payments.product",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="payments.product",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_user", "status"], name="payments_su_stripe__adb5e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["active", "freq"], name="payments_pr_active_77e7a8_idx"
            ),
        ),
    ]
