version: '3'
services:
  newsltr-db:
    image: postgres:latest
    container_name: newsltr-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsltr
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_API_KEY} --device-name Newsltr.io --forward-to newsltr-api:8000/api/v1/payments/webhook"
    environment:
      - STRIPE_API_KEY
      - STRIPE_DEVICE_NAME
  newsltr-redis:
    image: redis:latest
    container_name: newsltr-redis
    ports:
      - "6379:6379"
  newsltr-api:
    build:
      context: ./newsltr
      dockerfile: dev.Dockerfile
    image: newsltr-api:latest
    container_name: newsltr-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@newsltr-db:5432/newsltr
      REDIS_URL: redis://newsltr-redis:6379
    depends_on:
      - newsltr-db
      - newsltr-redis
      - stripe-cli
  newsltr-celery:
    build:
      context: ./newsltr
      dockerfile: dev.Dockerfile
    image: newsltr-celery:latest
    container_name: newsltr-celery
    command: celery -A newsltr worker -l info
    depends_on:
      - newsltr-api
    links:
      - newsltr-api