import Provider from "@/redux/Provider";
import Navbar from "@/components/Navbar";
import Setup from "@/utils/Setup";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar />
          <div>{children}</div>
          <Setup />
        </Provider>
      </body>
    </html>
  );
}
