import Provider from "@/redux/Provider";
import Navbar from "@/components/Navbar";
import "../globals.css";
import Setup from "@/utils/Setup";
import { Nunito_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("bg-bg-1 bg-left-top bg-no-repeat", nunitoSans.className)}
      >
        <Provider>
          <div className="">
            <Navbar />
            <div>{children}</div>
            <Setup />
          </div>
        </Provider>
      </body>
    </html>
  );
}
