# Generated by Django 4.2.6 on 2023-11-02 21:22

from django.db import migrations, models
import django.db.models.deletion
import trix.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0002_alter_campaign_workspace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=998, verbose_name="subject")),
                ("content", trix.fields.TrixField()),
                ("extra_data", models.JSONField()),
                ("last_sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tempaltes",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template",
                "ordering": ["id"],
            },
        ),
    ]
