# Generated by Django 4.2.7 on 2024-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                default="Untitled", max_length=250, verbose_name="name"
            ),
        ),
    ]
