# Generated by Django 4.2.5 on 2023-09-28 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
