# Generated by Django 4.2.5 on 2023-09-28 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0002_user_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
