# Generated by Django 4.2.5 on 2023-09-28 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0003_remove_user_id_alter_user_temp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="temp_id",
            new_name="id",
        ),
    ]
