# Generated by Django 4.2.5 on 2023-09-28 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0004_rename_temp_id_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
