# Generated by Django 4.2.5 on 2023-09-29 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
