# Generated by Django 4.2.6 on 2023-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
        ("authorization", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workspaces",
            field=models.ManyToManyField(
                related_name="members",
                related_query_name="member",
                through="workspaces.WorkspaceMembership",
                to="workspaces.workspace",
            ),
        ),
    ]
