# Generated by Django 4.2.7 on 2023-11-13 15:50

import authorization.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0008_user_workspaces"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authorization.models.AbstractUserManager()),
            ],
        ),
    ]
