# Generated by Django 4.2.6 on 2023-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="description",
            field=models.CharField(
                max_length=1024, verbose_name="workspace description"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(max_length=120, verbose_name="workspace name"),
        ),
    ]
