# Generated by Django 4.2.6 on 2023-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_workspaceapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceapikey",
            name="key",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Key",
            ),
        ),
    ]
