# Generated by Django 4.2.6 on 2023-10-18 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_workspaceapikey_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkspaceAPIKey",
        ),
    ]
