name: API Pre-Deploy

on:
  push:
    paths:
      - 'newsltr/**'
      - '.github/workflows/**'
    branches:
      - main
      - master
      - develop
  pull_request:
    paths:
      - 'newsltr/**'
      - '.github/workflows/**'
    branches:
      - main
      - master
      - develop

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 

      - name: Install dependencies
        run: |
          pip install -r newsltr/requirements.txt
          pip install flake8

      - name: Lint Python code
        working-directory: newsltr
        run: |
          flake8 .
          
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
      STRIPE_SECRET_KEY_TEST: ${{ secrets.STRIPE_SECRET_KEY_TEST }}
      STRIPE_PUBLISHABLE_KEY_TEST: ${{ secrets.STRIPE_PUBLISHABLE_KEY_TEST }}
      working-directory: ./newsltr

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Django Test CI   
        uses: UKnowWhoIm/django-test-action@v0.6.1
        with:
          settings-dir-path: newsltr
          requirements-file: requirements.txt
          parallel-tests: true